import { writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import type { StackInfo } from '../analyzers/stack-detector.js';

async function ensureDir(filePath: string) {
  await mkdir(dirname(filePath), { recursive: true });
}

function getBaseRules(stack: StackInfo): string[] {
  const lines: string[] = [
    '## General Guidelines',
    '',
    '- **Token Optimization Priority**: Read only the necessary context. Do not read entire directories or large lockfiles unless explicitly requested.',
    '- **Be concise**: Give direct answers. Do not repeat code that already exists in the project unless modifying it.',
    '- **Be modular**: Write small, focused functions with clear responsibilities.',
    '- **Follow existing patterns**: Match the coding style, naming conventions, and patterns already used in this codebase.',
    '- **Prefer edits over rewrites**: When modifying code, show only the changed parts or use strict replacements.',
    '',
  ];

  if (stack.language === 'TypeScript' || stack.language === 'JavaScript') {
    lines.push(
      `## Stack: ${stack.name}`,
      '',
      '- Use **ES Modules** (`import`/`export`) — not CommonJS (`require`).',
      '- Prefer `const` over `let`. Never use `var`.',
      '- Use **async/await** over raw Promises or callbacks.',
      '- Use optional chaining (`?.`) and nullish coalescing (`??`).',
      '- Handle errors gracefully with try/catch.',
    );

    if (stack.frameworks && stack.frameworks.length > 0) {
      if (stack.frameworks.includes('React') || stack.frameworks.includes('Next.js')) {
        lines.push(
          '- Write functional React components using hooks.',
          '- Keep effect dependencies accurate.',
        );
      }
      if (stack.frameworks.includes('Next.js')) {
        lines.push(
          '- Follow Next.js App Router conventions (`page.tsx`, `layout.tsx`).',
        );
      }
      if (stack.frameworks.includes('Vue') || stack.frameworks.includes('Nuxt')) {
        lines.push('- Use Vue 3 Composition API with `<script setup>`.');
      }
    }

    if (stack.hasTypeScript) {
      lines.push(
        '- Define explicit **TypeScript types** for function parameters and return values.',
        '- Use `interface` for object shapes, `type` for unions/intersections.',
        '- Avoid `any` — use `unknown` when the type is truly uncertain.',
      );
    }
  } else if (stack.language === 'Python') {
    lines.push(
      `## Stack: ${stack.name}`,
      '',
      '- Use **type hints** for all function signatures.',
      '- Follow **PEP 8** style conventions.',
      '- Prefer **pathlib** over os.path for file operations.',
    );
  } else if (stack.language === 'Rust') {
    lines.push(
      `## Stack: ${stack.name}`,
      '',
      '- Follow **Rust idioms**: use `Result<T, E>` for error handling.',
      '- Minimize `.unwrap()` and `.expect()` — propagate errors with `?`.',
    );
  } else if (stack.language === 'Go') {
    lines.push(
      `## Stack: ${stack.name}`,
      '',
      '- Follow **Go conventions**: explicitly handle errors.',
      '- Use `context.Context` for cancellation and timeouts.',
    );
  }

  lines.push('');
  return lines;
}

function getCursorRules(stack: StackInfo): string {
  const content = [
    '# .cursorrules — Generated by ContextSlim',
    '',
    '> AI behavior rules optimized for Cursor to minimize token usage and maximize output quality.',
    '',
    ...getBaseRules(stack),
    '## Cursor Specific Instructions',
    '- Do not attempt to summarize or explain unchanged code.',
    '- Use codebase indexing effectively; do not brute-force read files.',
    '- Verify types and lint rules before providing a code block.',
  ];
  return content.join('\n');
}

function getAntigravityWorkflow(stack: StackInfo): string {
  const content = [
    '---',
    'description: Standard Coding Guidelines and Context Management',
    '---',
    '',
    '# Antigravity Workflow: Coding & Context',
    '',
    ...getBaseRules(stack),
    '## Antigravity Specific Instructions',
    '- Use `grep_search` and `find_by_name` to locate files instead of heavy `list_dir` or reading large files.',
    '- When editing exactly 1 contiguous block, use `replace_file_content`.',
    '- Keep line ranges tight to save tokens.',
    '- For new functionalities, verify by running tests or the compiler via `run_command` if safe.',
  ];
  return content.join('\n');
}

function getCopilotInstructions(stack: StackInfo): string {
  const content = [
    '# GitHub Copilot Custom Instructions',
    '',
    ...getBaseRules(stack),
  ];
  return content.join('\n');
}

export async function generateRulesFiles(
  dir: string,
  stack: StackInfo,
): Promise<string[]> {
  const createdFiles: string[] = [];

  // 1. Cursor Rules
  const cursorPath = join(dir, '.cursorrules');
  await ensureDir(cursorPath);
  await writeFile(cursorPath, getCursorRules(stack), 'utf-8');
  createdFiles.push('.cursorrules');

  // 2. Antigravity Workflow
  const antigravityPath = join(dir, '.agents', 'workflows', 'coding_guidelines.md');
  await ensureDir(antigravityPath);
  await writeFile(antigravityPath, getAntigravityWorkflow(stack), 'utf-8');
  createdFiles.push('.agents/workflows/coding_guidelines.md');

  // 3. GitHub Copilot Instructions
  const copilotPath = join(dir, '.github', 'copilot-instructions.md');
  await ensureDir(copilotPath);
  await writeFile(copilotPath, getCopilotInstructions(stack), 'utf-8');
  createdFiles.push('.github/copilot-instructions.md');

  return createdFiles;
}
