import { writeFile, readFile, mkdir } from 'node:fs/promises';
import { join, dirname, basename } from 'node:path';
import { homedir } from 'node:os';
import type { StackInfo } from '../analyzers/stack-detector.js';
import { detectEntryPoints, generateMiniTree } from '../analyzers/project-context.js';

async function ensureDir(filePath: string) {
  await mkdir(dirname(filePath), { recursive: true });
}

function getBaseRules(stack: StackInfo): string[] {
  const lines: string[] = [
    '## General Guidelines',
    '',
    '- **Token Optimization Priority**: Read only the necessary context. Do not read entire directories or large lockfiles unless explicitly requested.',
    '- **Use AI-Optimized Commands**: When exploring the terminal, PREFER `npx contextslim tree [dir]` or `npx contextslim ls [dir]` instead of standard `tree` or `ls`. When reading files, PREFER `npx contextslim cat <file>` instead of `cat`. When making text searches, PREFER `npx contextslim grep <query>`. To understand the skeleton of a file without reading logic, STRICTLY use `npx contextslim map <file>`.',
    '- **Be concise**: Give direct answers. Do not repeat code that already exists in the project unless modifying it.',
    '- **Be modular**: Write small, focused functions with clear responsibilities.',
    '- **Follow existing patterns**: Match the coding style, naming conventions, and patterns already used in this codebase.',
    '- **Prefer edits over rewrites**: When modifying code, show only the changed parts or use strict replacements.',
    '',
  ];

  if (stack.language === 'TypeScript' || stack.language === 'JavaScript') {
    lines.push(
      `## Stack: ${stack.name}`,
      '',
      '- Use **ES Modules** (`import`/`export`) — not CommonJS (`require`).',
      '- Prefer `const` over `let`. Never use `var`.',
      '- Use **async/await** over raw Promises or callbacks.',
      '- Use optional chaining (`?.`) and nullish coalescing (`??`).',
      '- Handle errors gracefully with try/catch.',
    );

    if (stack.frameworks && stack.frameworks.length > 0) {
      if (stack.frameworks.includes('React') || stack.frameworks.includes('Next.js')) {
        lines.push(
          '- Write functional React components using hooks.',
          '- Keep effect dependencies accurate.',
        );
      }
      if (stack.frameworks.includes('Next.js')) {
        lines.push(
          '- Follow Next.js App Router conventions (`page.tsx`, `layout.tsx`).',
        );
      }
      if (stack.frameworks.includes('Vue') || stack.frameworks.includes('Nuxt')) {
        lines.push('- Use Vue 3 Composition API with `<script setup>`.');
      }
    }

    if (stack.hasTypeScript) {
      lines.push(
        '- Define explicit **TypeScript types** for function parameters and return values.',
        '- Use `interface` for object shapes, `type` for unions/intersections.',
        '- Avoid `any` — use `unknown` when the type is truly uncertain.',
      );
    }
  } else if (stack.language === 'Python') {
    lines.push(
      `## Stack: ${stack.name}`,
      '',
      '- Use **type hints** for all function signatures.',
      '- Follow **PEP 8** style conventions.',
      '- Prefer **pathlib** over os.path for file operations.',
    );
  } else if (stack.language === 'Rust') {
    lines.push(
      `## Stack: ${stack.name}`,
      '',
      '- Follow **Rust idioms**: use `Result<T, E>` for error handling.',
      '- Minimize `.unwrap()` and `.expect()` — propagate errors with `?`.',
    );
  } else if (stack.language === 'Go') {
    lines.push(
      `## Stack: ${stack.name}`,
      '',
      '- Follow **Go conventions**: explicitly handle errors.',
      '- Use `context.Context` for cancellation and timeouts.',
    );
  }

  lines.push('');
  return lines;
}

function getCursorRules(stack: StackInfo): string {
  const content = [
    '# .cursorrules — Generated by ContextSlim',
    '',
    '> AI behavior rules optimized for Cursor to minimize token usage and maximize output quality.',
    '',
    ...getBaseRules(stack),
    '## Cursor Specific Instructions',
    '- Do not attempt to summarize or explain unchanged code.',
    '- Use codebase indexing effectively; do not brute-force read files.',
    '- Verify types and lint rules before providing a code block.',
  ];
  return content.join('\n');
}

function getAntigravityRules(stack: StackInfo): string {
  const content = [
    '---',
    'description: General rules and instructions for Antigravity — Generated by ContextSlim',
    '---',
    '# ContextSlim Workflow Guide',
    '',
    '> Project-specific context (stack, entry points, structure) is in `.agent/rules/general.md`.',
    '',

    // ── Progressive Context ────────────────────────────────────
    '## Progressive Context — Always Start Low',
    '',
    'Escalate depth only when needed:',
    '',
    '1. `npx contextslim tree . 2` → Project structure (~50 tokens)',
    '2. `npx contextslim map <file>` → Function/class signatures only (~30 tokens)',
    '3. `view_file` (native, with line ranges) → Read specific sections',
    '4. `view_file` (full file) → Only when you truly need everything',
    '',
    'NEVER jump to step 3-4 without trying 1-2 first, unless you already know the exact file and lines.',
    '',

    // ── Command Reference (compact table) ──────────────────────
    '## ContextSlim Commands',
    '',
    '| Command | When to Use |',
    '|---------|-------------|',
    '| `npx contextslim tree [dir] [depth]` | First exploration. Clean tree hiding node_modules/dist/.git etc. Default depth: 3 |',
    '| `npx contextslim ls [dir]` | List one directory, hiding heavy folders |',
    '| `npx contextslim map <file>` | Extract signatures (functions, classes, types). Use BEFORE reading a file. 500 lines → ~20 lines |',
    '| `npx contextslim cat <file>` | Terminal-only file read. Strips blanks, truncates at 150 lines. **Never use before editing** |',
    '| `npx contextslim grep <q> [dir]` | Terminal-only search. Max 5 matches/file, 50 total. Skips heavy dirs |',
    '| `npx contextslim init` | Generate ignore files + AI rules. Safe to re-run |',
    '| `npx contextslim scan` | Estimate token waste from heavy directories |',
    '| `npx contextslim doctor` | Check if AI optimization files exist |',
    '',

    // ── Native vs ContextSlim ──────────────────────────────────
    '## When to Use Native Antigravity Tools vs ContextSlim',
    '',
    '| Task | Use This | Not This |',
    '|------|----------|----------|',
    '| Read file | `view_file` (native) | `contextslim cat` |',
    '| Search text | `grep_search` (native) | `contextslim grep` |',
    '| Find files | `find_by_name` (native) | terminal `find` |',
    '| Explore tree | `contextslim tree` | terminal `tree`/`ls -R` |',
    '| List dir | `contextslim ls` | terminal `ls`/`dir` |',
    '| File structure | `contextslim map` | Reading entire file |',
    '',
    'Use ContextSlim terminal commands only when you need terminal pipelines or the native tool is unavailable.',
    '',

    // ── Safe Editing ────────────────────────────────────────────
    '## ⚠️ Safe Editing (CRITICAL)',
    '',
    '- **ALWAYS** `view_file` BEFORE editing. Never edit based on `contextslim cat` — it may be truncated.',
    '- If `cat` showed ✂️ TRUNCATED and you need the hidden zone → `view_file` the full file first.',
    '- Before `replace_file_content`, confirm you have exact current content from `view_file`.',
    '- User asks "show full file" → use `view_file`, never truncating `cat`.',
    '',

    // ── File Types ──────────────────────────────────────────────
    '## File Handling Strategy',
    '',
    '| Type | Action |',
    '|------|--------|',
    '| Config (tsconfig, eslint, vite) | `view_file` directly (small, need exact content) |',
    '| Source code (.ts .js .py .rs .go) | `map` first → `view_file` specific lines |',
    '| Tests (*test*, *spec*) | Skip unless user asks |',
    '| Docs (.md .txt) | `view_file` directly |',
    '| package.json | `contextslim cat` (summary only) |',
    '| Lockfiles, .env, assets, .d.ts | **NEVER READ** |',
    '',

    // ── NEVER Rules ────────────────────────────────────────────
    '## NEVER Rules',
    '',
    '- NEVER read `node_modules/`, `dist/`, `build/`, `.git/`, `coverage/`, `venv/`, `vendor/`.',
    '- NEVER read lockfiles, `.env`, secrets, auto-generated files.',
    '- NEVER use `contextslim cat` before editing — use `view_file`.',
    '- NEVER use `contextslim cat` for files <50 lines — use `view_file`.',
    '- NEVER use raw `tree` or `ls -R` in terminal — use `contextslim tree`.',
    '- NEVER read the full file when `map` answers the question.',
    '',

    // ── Smart Search ────────────────────────────────────────────
    '## Smart Search',
    '',
    'Before searching: 1) Did `tree` show it? 2) Framework conventions? (Next.js → `app/`, Vue → `src/components/`) 3) Did `map` show the import? → Only then use `grep_search` native.',
    '',

    // ── Efficiency Rules ────────────────────────────────────────
    '## Efficiency Rules',
    '',
    '- Don\'t repeat `tree` or `map` in the same conversation.',
    '- Group file reads — don\'t re-run `tree` between each.',
    '- Don\'t echo back the full file content to the user.',
    '- Show diffs, not full rewrites, for small changes.',
    '- Max ~5 file reads per interaction. Ask user before reading more.',
    '- Files >500 lines → `map` first, then `view_file` with targeted line ranges.',
    '',

    // ── Error Recovery ──────────────────────────────────────────
    '## Error Recovery',
    '',
    '- ContextSlim command fails → Fall back to native tool (`view_file`, `grep_search`, `list_dir`).',
    '- `contextslim grep` no results → Try `grep_search` native (broader reach).',
    '- `contextslim tree` missing a dir → Might be in ignore patterns, use `list_dir` native.',
    '- `contextslim map` no signatures → Non-standard syntax, use `view_file` directly.',
  ];
  return content.join('\n');
}

function getClaudeRules(stack: StackInfo): string {
  const content = [
    '# Claude Code Project Context',
    '',
    ...getBaseRules(stack),
    '## Claude Specific Instructions',
    '- Provide code edits without outputting the entire file.',
    '- Avoid rambling explanations before writing code.',
    '- Stay in character as a senior developer maintaining this exact stack.',
  ];
  return content.join('\n');
}

function getCopilotInstructions(stack: StackInfo): string {
  const content = [
    '# GitHub Copilot Custom Instructions',
    '',
    ...getBaseRules(stack),
  ];
  return content.join('\n');
}

// ── Local Project-Specific Rules ────────────────────────────────

async function getLocalAntigravityRules(
  dir: string,
  stack: StackInfo,
): Promise<string> {
  const lines: string[] = [
    '---',
    'description: Project-specific context and rules for Antigravity — Generated by ContextSlim',
    '---',
    '# Project Context',
    '',
    '> This file is auto-generated by ContextSlim. It gives the AI context about THIS specific project.',
    '> For ContextSlim command usage, see the global workflow: `~/.gemini/antigravity/global_workflows/contextslim_rules.md`',
    '',
  ];

  // ── Stack Info ──
  lines.push(
    '## Stack',
    '',
    `- **Detected**: ${stack.name}`,
    `- **Language**: ${stack.language}`,
    `- **TypeScript**: ${stack.hasTypeScript ? 'Yes' : 'No'}`,
  );

  if (stack.frameworks.length > 0) {
    lines.push(`- **Frameworks**: ${stack.frameworks.join(', ')}`);
  }

  lines.push(`- **Detected files**: ${stack.detectedFiles.join(', ')}`, '');

  // ── Entry Points ──
  const entryPoints = await detectEntryPoints(dir, stack);
  if (entryPoints.length > 0) {
    lines.push('## Entry Points', '');
    for (const ep of entryPoints) {
      lines.push(`- \`${ep.file}\` — ${ep.label}`);
    }
    lines.push('');
  }

  // ── Mini Tree ──
  const miniTree = await generateMiniTree(dir, 2);
  if (miniTree.trim()) {
    lines.push(
      '## Project Structure',
      '',
      '```',
      basename(dir) + '/',
      miniTree,
      '```',
      '',
    );
  }

  // ── Project Conventions (from stack) ──
  lines.push('## Project Conventions', '');

  if (stack.language === 'TypeScript' || stack.language === 'JavaScript') {
    lines.push(
      '- Use **ES Modules** (`import`/`export`) — not CommonJS (`require`).',
      '- Prefer `const` over `let`. Never use `var`.',
      '- Use **async/await** over raw Promises or callbacks.',
      '- Use optional chaining (`?.`) and nullish coalescing (`??`).',
    );
    if (stack.hasTypeScript) {
      lines.push(
        '- Define explicit **TypeScript types** for function parameters and return values.',
        '- Use `interface` for object shapes, `type` for unions/intersections.',
        '- Avoid `any` — use `unknown` when the type is truly uncertain.',
      );
    }
    if (stack.frameworks.includes('React') || stack.frameworks.includes('Next.js')) {
      lines.push(
        '- Write functional React components using hooks.',
        '- Keep effect dependencies accurate.',
      );
    }
    if (stack.frameworks.includes('Next.js')) {
      lines.push('- Follow Next.js App Router conventions (`page.tsx`, `layout.tsx`).');
    }
    if (stack.frameworks.includes('Vue') || stack.frameworks.includes('Nuxt')) {
      lines.push('- Use Vue 3 Composition API with `<script setup>`.');
    }
    if (stack.frameworks.includes('NestJS')) {
      lines.push(
        '- Use decorators and dependency injection.',
        '- Follow NestJS module/controller/service pattern.',
      );
    }
  } else if (stack.language === 'Python') {
    lines.push(
      '- Use **type hints** for all function signatures.',
      '- Follow **PEP 8** style conventions.',
      '- Prefer **pathlib** over os.path for file operations.',
    );
  } else if (stack.language === 'Rust') {
    lines.push(
      '- Follow **Rust idioms**: use `Result<T, E>` for error handling.',
      '- Minimize `.unwrap()` and `.expect()` — propagate errors with `?`.',
    );
  } else if (stack.language === 'Go') {
    lines.push(
      '- Follow **Go conventions**: explicitly handle errors.',
      '- Use `context.Context` for cancellation and timeouts.',
    );
  } else if (stack.language === 'PHP') {
    lines.push(
      '- Follow **PSR-12** coding style.',
      '- Use type declarations for parameters and return types.',
    );
  } else if (stack.language === 'Ruby') {
    lines.push(
      '- Follow **Ruby style guide** conventions.',
      '- Use `frozen_string_literal: true` pragma.',
    );
  } else if (stack.language === 'Java') {
    lines.push(
      '- Follow **Java naming conventions** (camelCase methods, PascalCase classes).',
      '- Use try-with-resources for AutoCloseable objects.',
    );
  }

  lines.push('');

  return lines.join('\n');
}

import type { ContextSlimConfig } from '../utils/config.js';

export async function generateRulesFiles(
  dir: string,
  stack: StackInfo,
  config?: ContextSlimConfig
): Promise<string[]> {
  const createdFiles: string[] = [];

  const safeWrite = async (filePath: string, content: string, fileName: string) => {
    let existingContent = '';
    try {
      existingContent = await readFile(filePath, 'utf-8');
    } catch {}

    if (existingContent && !existingContent.includes('Generated by ContextSlim')) {
      await writeFile(filePath, existingContent + '\n\n' + content, 'utf-8');
    } else if (!existingContent) {
      await writeFile(filePath, content, 'utf-8');
    }
    createdFiles.push(fileName);
  };

  // Always overwrite files marked as generated by ContextSlim
  const generatedWrite = async (filePath: string, content: string, fileName: string) => {
    let existingContent = '';
    try {
      existingContent = await readFile(filePath, 'utf-8');
    } catch {}

    if (!existingContent || existingContent.includes('Generated by ContextSlim')) {
      await ensureDir(filePath);
      await writeFile(filePath, content, 'utf-8');
    } else {
      // User file exists without our marker — append
      await writeFile(filePath, existingContent + '\n\n' + content, 'utf-8');
    }
    createdFiles.push(fileName);
  };

  const ides = config?.ides || ['cursor', 'antigravity', 'claude', 'copilot'];

  // 1. Cursor Rules
  if (ides.includes('cursor')) {
    const cursorPath = join(dir, '.cursorrules');
    await ensureDir(cursorPath);
    await safeWrite(cursorPath, getCursorRules(stack), '.cursorrules');
  }

  // 2. Antigravity Global Rules & 3. Local Rules
  if (ides.includes('antigravity')) {
    const antigravityGlobalPath = join(homedir(), '.gemini', 'antigravity', 'global_workflows', 'contextslim_rules.md');
    await ensureDir(antigravityGlobalPath);
    await generatedWrite(antigravityGlobalPath, getAntigravityRules(stack), 'Global Antigravity Rules (contextslim_rules.md)');

    const antigravityLocalPath = join(dir, '.agent', 'rules', 'general.md');
    const localContent = await getLocalAntigravityRules(dir, stack);
    await generatedWrite(antigravityLocalPath, localContent, 'Local Antigravity Rules (.agent/rules/general.md)');
  }

  // 4. GitHub Copilot Instructions
  if (ides.includes('copilot')) {
    const copilotPath = join(dir, '.github', 'copilot-instructions.md');
    await ensureDir(copilotPath);
    await safeWrite(copilotPath, getCopilotInstructions(stack), '.github/copilot-instructions.md');
  }

  // 5. Claude Code / CLAUDE.md
  if (ides.includes('claude')) {
    const claudePath = join(dir, 'CLAUDE.md');
    await ensureDir(claudePath);
    await safeWrite(claudePath, getClaudeRules(stack), 'CLAUDE.md');
  }

  return createdFiles;
}
