import { writeFile, readFile, mkdir } from 'node:fs/promises';
import { join, dirname, basename } from 'node:path';
import { homedir } from 'node:os';
import type { StackInfo } from '../analyzers/stack-detector.js';
import { detectEntryPoints, generateMiniTree } from '../analyzers/project-context.js';
import { generateBriefText } from '../commands/brief.js';

async function ensureDir(filePath: string) {
  await mkdir(dirname(filePath), { recursive: true });
}

function getBaseRules(stack: StackInfo): string[] {
  const lines: string[] = [
    '## General Guidelines',
    '',
    '- **Token Optimization Priority**: Read only the necessary context. Do not read entire directories or large lockfiles unless explicitly requested.',
    '- **Use AI-Optimized Commands**: ALWAYS prefer ContextSlim commands over standard tools. `contextslim tree` over `tree`, `contextslim map` over reading full files, `contextslim grep` over `grep`, `contextslim outline` for full codebase, `contextslim imports` for deps, `contextslim types` for TS types, `contextslim deps` for packages, `contextslim head` for quick peeks, `contextslim logs` over `cat log`, `contextslim ports` over `netstat`/`ss`, `contextslim disk` over `df`/`du`, `contextslim docker` over `docker ps`, `contextslim packages` over `dpkg -l`/`rpm -qa`, `contextslim findfiles` over `find`, `contextslim run` with timeout for hanging scripts.',
    '',
    '## ⚠️ CONCISENESS — MANDATORY (CRITICAL)',
    '',
    '- **MAX 3 LINES** after completing a task. Say WHAT you did, not HOW or WHY.',
    '- **NEVER** write paragraphs explaining code. The code speaks for itself.',
    '- **NEVER** use analogies, metaphors, or educational explanations.',
    '- **NEVER** repeat back what the user said or summarize the problem.',
    '- **NEVER** list multiple options unless the user explicitly asks for alternatives.',
    '- **NEVER** explain concepts the user already knows (they are a developer).',
    '- **DO NOT** narrate your thinking process. Just do the work and report the result.',
    '- If the user asks to fix something → fix it, say "Fixed X in Y file" and STOP.',
    '- If the user asks to add something → add it, say "Added X to Y" and STOP.',
    '',
    '## General Guidelines',
    '',
    '- **Be modular**: Write small, focused functions with clear responsibilities.',
    '- **Follow existing patterns**: Match the coding style, naming conventions, and patterns already used in this codebase.',
    '- **Prefer edits over rewrites**: When modifying code, show only the changed parts or use strict replacements.',
    '',
  ];

  if (stack.language === 'TypeScript' || stack.language === 'JavaScript') {
    lines.push(
      `## Stack: ${stack.name}`,
      '',
      '- Use **ES Modules** (`import`/`export`) — not CommonJS (`require`).',
      '- Prefer `const` over `let`. Never use `var`.',
      '- Use **async/await** over raw Promises or callbacks.',
      '- Use optional chaining (`?.`) and nullish coalescing (`??`).',
      '- Handle errors gracefully with try/catch.',
    );

    if (stack.frameworks && stack.frameworks.length > 0) {
      if (stack.frameworks.includes('React') || stack.frameworks.includes('Next.js')) {
        lines.push(
          '- Write functional React components using hooks.',
          '- Keep effect dependencies accurate.',
        );
      }
      if (stack.frameworks.includes('Next.js')) {
        lines.push(
          '- Follow Next.js App Router conventions (`page.tsx`, `layout.tsx`).',
        );
      }
      if (stack.frameworks.includes('Vue') || stack.frameworks.includes('Nuxt')) {
        lines.push('- Use Vue 3 Composition API with `<script setup>`.');
      }
    }

    if (stack.hasTypeScript) {
      lines.push(
        '- Define explicit **TypeScript types** for function parameters and return values.',
        '- Use `interface` for object shapes, `type` for unions/intersections.',
        '- Avoid `any` — use `unknown` when the type is truly uncertain.',
      );
    }
  } else if (stack.language === 'Python') {
    lines.push(
      `## Stack: ${stack.name}`,
      '',
      '- Use **type hints** for all function signatures.',
      '- Follow **PEP 8** style conventions.',
      '- Prefer **pathlib** over os.path for file operations.',
    );
  } else if (stack.language === 'Rust') {
    lines.push(
      `## Stack: ${stack.name}`,
      '',
      '- Follow **Rust idioms**: use `Result<T, E>` for error handling.',
      '- Minimize `.unwrap()` and `.expect()` — propagate errors with `?`.',
    );
  } else if (stack.language === 'Go') {
    lines.push(
      `## Stack: ${stack.name}`,
      '',
      '- Follow **Go conventions**: explicitly handle errors.',
      '- Use `context.Context` for cancellation and timeouts.',
    );
  }

  lines.push('');
  return lines;
}

function getCursorRules(stack: StackInfo, briefText: string): string {
  const content = [
    '# .cursorrules — Generated by ContextSlim',
    '',
    '> AI behavior rules optimized for Cursor to minimize token usage and maximize output quality.',
    '',
    '## Project Brief',
    '```text',
    briefText,
    '```',
    '',
    ...getBaseRules(stack),
    '## Cursor Specific Instructions',
    '- Do not attempt to summarize or explain unchanged code.',
    '- Use codebase indexing effectively; do not brute-force read files.',
    '- Verify types and lint rules before providing a code block.',
  ];
  return content.join('\n');
}

function getAntigravityRules(stack: StackInfo): string {
  const content = [
    '---',
    'description: General rules and instructions for Antigravity — Generated by ContextSlim',
    '---',
    '# ContextSlim Global Rules',
    '',
    '> Project-specific context (stack, entry points, structure) is in `.agent/rules/general.md`.',
    '',

    // ── CONCISENESS ────────────────────────────────────────────
    '## ⚠️ CONCISENESS — MANDATORY (CRITICAL)',
    '',
    '- **MAX 3 LINES** after completing a task. Say WHAT you did, not HOW or WHY.',
    '- **NEVER** write paragraphs explaining code. The code speaks for itself.',
    '- **NEVER** use analogies, metaphors, or educational explanations.',
    '- **NEVER** repeat back what the user said or summarize the problem.',
    '- **NEVER** list multiple options unless the user explicitly asks.',
    '- **DO NOT** narrate your thinking process. Just do the work and report.',
    '- Fix something → say "Fixed X in Y" and STOP. Add something → say "Added X to Y" and STOP.',
    '',

    // ── Progressive Context ────────────────────────────────────
    '## Progressive Context — Always Start Low',
    '',
    'Escalate depth only when needed:',
    '',
    '1. `npx contextslim tree . 2` → Project structure (~50 tokens)',
    '2. `npx contextslim map <file>` → Function/class signatures only (~30 tokens)',
    '3. `view_file` (native, with line ranges) → Read specific sections',
    '4. `view_file` (full file) → Only when you truly need everything',
    '',
    'NEVER jump to step 3-4 without trying 1-2 first, unless you already know the exact file and lines.',
    '',

    // ── Command Reference (compact table) ──────────────────────
    '## ContextSlim Commands',
    '',
    '### Exploration',
    '| Command | When to Use |',
    '|---------|-------------|',
    '| `contextslim tree [dir] [depth]` | First exploration. Clean tree hiding node_modules/dist/.git etc. Default depth: 3 |',
    '| `contextslim ls [dir]` | List one directory, hiding heavy folders |',
    '| `contextslim brief [dir]` | ~300-token project summary. Use at conversation start |',
    '| `contextslim outline [dir]` | **Recursive map** of ALL source files. Full codebase architecture in one shot (~82% savings) |',
    '',
    '### OS & DB Optimization',
    '| Command | When to Use |',
    '|---------|-------------|',
    '| `contextslim sysinfo` | Compact system info replacing systeminfo/uname (~90% savings) |',
    '| `contextslim procs [filter]` | Compact sorted process list replacing tasklist/ps aux (~90% savings) |',
    '| `contextslim dbschema <conn> [filter]` | Compact database schema tree, skipping huge text dumps (~90% savings) |',
    '| `contextslim dbquery <query> <conn>` | Optimized SQL execution that truncates massive tables and long columns |',
    '| `contextslim dbstats <conn> [filter]` | DB size, rows and tables in a compact table |',
    '',
    '### File Reading',
    '| Command | When to Use |',
    '|---------|-------------|',
    '| `contextslim map <file>` | Extract signatures only. Use BEFORE reading a file. 500 lines → ~20 lines |',
    '| `contextslim cat <file>` | Terminal-only read. Strips blanks, truncates at 150 lines. **Never use before editing** |',
    '| `contextslim head <file> [n]` | Show first N lines (default 30). Quick peek at imports/headers |',
    '| `contextslim imports <file>` | Extract ONLY import/require statements (~96% savings). Use to understand dependencies |',
    '| `contextslim types <file>` | Extract ONLY TypeScript interfaces/types/enums (~81% savings) |',
    '',
    '### Search & Analysis',
    '| Command | When to Use |',
    '|---------|-------------|',
    '| `contextslim grep <q> [dir]` | Terminal-only search. Max 5 matches/file, 50 total. Skips heavy dirs |',
    '| `contextslim todo [dir]` | Find all TODO/FIXME/HACK/BUG comments. Instant pending-work context |',
    '| `contextslim deps` | Compact dependency list from package.json. No version noise (~66% savings) |',
    '| `contextslim diff [target]` | AI-optimized git diff, stripping lockfiles and build artifacts |',
    '',
    '### Debugging & Execution',
    '| Command | When to Use |',
    '|---------|-------------|',
    '| `contextslim run <cmd> --timeout N` | Run a command with auto-kill after N seconds. Catches hanging scripts |',
    '| `contextslim tail <file> --time N` | Stream log file for N seconds, then stop. Captures pre-crash output |',
    '| `contextslim logs <file> [lines]` | Last N lines of a log, timestamps stripped (~70% savings) |',
    '| `contextslim errors <file>` | Extract ONLY error/warning lines from logs (~99% savings) |',
    '| `contextslim summary <file>` | Structured file summary — imports, exports, functions, size (~95% savings) |',
    '',
    '### Analysis & Comparison',
    '| Command | When to Use |',
    '|---------|-------------|',
    '| `contextslim changes [n]` | Compact git log — last N commits with changed files (~80% savings) |',
    '| `contextslim compare <file1> <file2>` | Compact diff between two files — only differences shown |',
    '| `contextslim config <file>` | Read config files stripping comments/blanks (~80% savings) |',
    '',
    '### Linux & Cross-Platform',
    '| Command | When to Use |',
    '|---------|-------------|',
    '| `contextslim ports [filter]` | Compact open ports — replaces netstat/ss (~80% savings) |',
    '| `contextslim disk [dir]` | Compact disk usage — replaces df + du (~85% savings) |',
    '| `contextslim docker [filter]` | Docker containers/images/volumes in one compact view (~80% savings) |',
    '| `contextslim packages [filter]` | Installed packages — replaces dpkg -l/rpm -qa/apk list (~90% savings) |',
    '| `contextslim findfiles <pattern> [dir]` | AI-optimized find — skips heavy dirs, caps at 30 results |',
    '',
    '### Setup & Metrics',
    '| Command | When to Use |',
    '|---------|-------------|',
    '| `contextslim init` | Generate ignore files + AI rules. Safe to re-run |',
    '| `contextslim scan` | Estimate token waste from heavy directories |',
    '| `contextslim doctor` | Check if AI optimization files exist |',
    '| `contextslim stats` | Measure exact token usage and savings |',
    '| `contextslim meter simulate` | Show what-if comparison: tokens with vs without ContextSlim |',
    '',

    // ── Native vs ContextSlim ──────────────────────────────────
    '## When to Use Native Antigravity Tools vs ContextSlim',
    '',
    '| Task | Use This | Not This |',
    '|------|----------|----------|',
    '| Read file for editing | `view_file` (native) | `contextslim cat` |',
    '| Read file to understand | `contextslim map` or `head` | `view_file` (full) |',
    '| Understand dependencies | `contextslim imports` | Reading full file |',
    '| See TypeScript types | `contextslim types` | Reading full file |',
    '| See full codebase architecture | `contextslim outline` | Multiple `map` calls |',
    '| Search text | `grep_search` (native) | `contextslim grep` |',
    '| Find pending work | `contextslim todo` | `grep_search TODO` |',
    '| Explore tree | `contextslim tree` | terminal `tree`/`ls -R` |',
    '| Check package info | `contextslim deps` | Reading package.json |',
    '',
    'Use ContextSlim terminal commands only when you need terminal pipelines or the native tool is unavailable.',
    '',

    // ── Safe Editing ────────────────────────────────────────────
    '## ⚠️ Safe Editing (CRITICAL)',
    '',
    '- **ALWAYS** `view_file` BEFORE editing. Never edit based on `contextslim cat` — it may be truncated.',
    '- If `cat` showed ✂️ TRUNCATED and you need the hidden zone → `view_file` the full file first.',
    '- Before `replace_file_content`, confirm you have exact current content from `view_file`.',
    '- User asks "show full file" → use `view_file`, never truncating `cat`.',
    '',

    // ── File Types ──────────────────────────────────────────────
    '## File Handling Strategy',
    '',
    '| Type | Action |',
    '|------|--------|',
    '| Config (tsconfig, eslint, vite) | `view_file` directly (small, need exact content) |',
    '| Source code (.ts .js .py .rs .go) | `map` first → `view_file` specific lines |',
    '| Source code (need only types) | `contextslim types` (TS only) |',
    '| Source code (need only imports) | `contextslim imports` |',
    '| Full directory of source files | `contextslim outline` (all signatures at once) |',
    '| Tests (*test*, *spec*) | Skip unless user asks |',
    '| Docs (.md .txt) | `view_file` directly |',
    '| package.json | `contextslim deps` (compact format) |',
    '| Lockfiles, .env, assets, .d.ts | **NEVER READ** |',
    '',

    // ── NEVER Rules ────────────────────────────────────────────
    '## NEVER Rules',
    '',
    '- NEVER read `node_modules/`, `dist/`, `build/`, `.git/`, `coverage/`, `venv/`, `vendor/`.',
    '- NEVER read lockfiles, `.env`, secrets, auto-generated files.',
    '- NEVER use `contextslim cat` before editing — use `view_file`.',
    '- NEVER use `contextslim cat` for files <50 lines — use `view_file`.',
    '- NEVER use raw `tree` or `ls -R` in terminal — use `contextslim tree`.',
    '- NEVER read the full file when `map` answers the question.',
    '- NEVER run `pm2 restart` or `node` servers in terminal without `--silent` or `> /dev/null 2>&1` (massive logs burn tokens).',
    '',

    // ── Smart Search ────────────────────────────────────────────
    '## Smart Search',
    '',
    'Before searching: 1) Did `tree` show it? 2) Framework conventions? (Next.js → `app/`, Vue → `src/components/`) 3) Did `map` show the import? → Only then use `grep_search` native.',
    '',

    // ── Efficiency Rules ────────────────────────────────────────
    '## Efficiency Rules',
    '',
    '- Don\'t repeat `tree` or `map` in the same conversation.',
    '- Group file reads — don\'t re-run `tree` between each.',
    '- Don\'t echo back the full file content to the user.',
    '- Show diffs, not full rewrites, for small changes.',
    '- Max ~5 file reads per interaction. Ask user before reading more.',
    '- Files >500 lines → `map` first, then `view_file` with targeted line ranges.',
    '',

    // ── Error Recovery ──────────────────────────────────────────
    '## Error Recovery',
    '',
    '- ContextSlim command fails → Fall back to native tool (`view_file`, `grep_search`, `list_dir`).',
    '- `contextslim grep` no results → Try `grep_search` native (broader reach).',
    '- `contextslim tree` missing a dir → Might be in ignore patterns, use `list_dir` native.',
    '- `contextslim map` no signatures → Non-standard syntax, use `view_file` directly.',
  ];
  return content.join('\n');
}

function getClaudeRules(stack: StackInfo, briefText: string): string {
  const content = [
    '# Claude Code Project Context',
    '',
    '## Project Brief',
    '```text',
    briefText,
    '```',
    '',
    ...getBaseRules(stack),
    '## Claude Specific Instructions',
    '- Provide code edits without outputting the entire file.',
    '- Avoid rambling explanations before writing code.',
    '- Stay in character as a senior developer maintaining this exact stack.',
  ];
  return content.join('\n');
}

function getCopilotInstructions(stack: StackInfo, briefText: string): string {
  const content = [
    '# GitHub Copilot Custom Instructions',
    '',
    '## Project Brief',
    '```text',
    briefText,
    '```',
    '',
    ...getBaseRules(stack),
  ];
  return content.join('\n');
}

// ── Local Project-Specific Rules ────────────────────────────────

function getLocalAntigravityRules(
  stack: StackInfo,
  briefText: string,
): string {
  const lines: string[] = [
    '---',
    'description: Project-specific context and rules for Antigravity — Generated by ContextSlim',
    '---',
    '# Project Context',
    '',
    '> This file is auto-generated by ContextSlim. It gives the AI context about THIS specific project.',
    '> For ContextSlim command usage, see the global rules: `~/.gemini/GEMINI.md`',
    '',
    '## Project Brief',
    '```text',
    briefText,
    '```',
    '',
  ];

  // ── Project Conventions (from stack) ──
  lines.push('## Project Conventions', '');

  if (stack.language === 'TypeScript' || stack.language === 'JavaScript') {
    lines.push(
      '- Use **ES Modules** (`import`/`export`) — not CommonJS (`require`).',
      '- Prefer `const` over `let`. Never use `var`.',
      '- Use **async/await** over raw Promises or callbacks.',
      '- Use optional chaining (`?.`) and nullish coalescing (`??`).',
    );
    if (stack.hasTypeScript) {
      lines.push(
        '- Define explicit **TypeScript types** for function parameters and return values.',
        '- Use `interface` for object shapes, `type` for unions/intersections.',
        '- Avoid `any` — use `unknown` when the type is truly uncertain.',
      );
    }
    if (stack.frameworks.includes('React') || stack.frameworks.includes('Next.js')) {
      lines.push(
        '- Write functional React components using hooks.',
        '- Keep effect dependencies accurate.',
      );
    }
    if (stack.frameworks.includes('Next.js')) {
      lines.push('- Follow Next.js App Router conventions (`page.tsx`, `layout.tsx`).');
    }
    if (stack.frameworks.includes('Vue') || stack.frameworks.includes('Nuxt')) {
      lines.push('- Use Vue 3 Composition API with `<script setup>`.');
    }
    if (stack.frameworks.includes('NestJS')) {
      lines.push(
        '- Use decorators and dependency injection.',
        '- Follow NestJS module/controller/service pattern.',
      );
    }
  } else if (stack.language === 'Python') {
    lines.push(
      '- Use **type hints** for all function signatures.',
      '- Follow **PEP 8** style conventions.',
      '- Prefer **pathlib** over os.path for file operations.',
    );
  } else if (stack.language === 'Rust') {
    lines.push(
      '- Follow **Rust idioms**: use `Result<T, E>` for error handling.',
      '- Minimize `.unwrap()` and `.expect()` — propagate errors with `?`.',
    );
  } else if (stack.language === 'Go') {
    lines.push(
      '- Follow **Go conventions**: explicitly handle errors.',
      '- Use `context.Context` for cancellation and timeouts.',
    );
  } else if (stack.language === 'PHP') {
    lines.push(
      '- Follow **PSR-12** coding style.',
      '- Use type declarations for parameters and return types.',
    );
  } else if (stack.language === 'Ruby') {
    lines.push(
      '- Follow **Ruby style guide** conventions.',
      '- Use `frozen_string_literal: true` pragma.',
    );
  } else if (stack.language === 'Java') {
    lines.push(
      '- Follow **Java naming conventions** (camelCase methods, PascalCase classes).',
      '- Use try-with-resources for AutoCloseable objects.',
    );
  }

  lines.push('');

  return lines.join('\n');
}

import type { ContextSlimConfig } from '../utils/config.js';

export async function generateRulesFiles(
  dir: string,
  stack: StackInfo,
  config?: ContextSlimConfig
): Promise<string[]> {
  const createdFiles: string[] = [];
  const briefText = await generateBriefText(dir, stack);

  const safeWrite = async (filePath: string, content: string, fileName: string) => {
    let existingContent = '';
    try {
      existingContent = await readFile(filePath, 'utf-8');
    } catch {}

    if (existingContent && !existingContent.includes('Generated by ContextSlim')) {
      await writeFile(filePath, existingContent + '\n\n' + content, 'utf-8');
    } else if (!existingContent) {
      await writeFile(filePath, content, 'utf-8');
    }
    createdFiles.push(fileName);
  };

  // Always overwrite files marked as generated by ContextSlim
  const generatedWrite = async (filePath: string, content: string, fileName: string) => {
    let existingContent = '';
    try {
      existingContent = await readFile(filePath, 'utf-8');
    } catch {}

    if (!existingContent || existingContent.includes('Generated by ContextSlim')) {
      await ensureDir(filePath);
      await writeFile(filePath, content, 'utf-8');
    } else {
      // User file exists without our marker — append
      await writeFile(filePath, existingContent + '\n\n' + content, 'utf-8');
    }
    createdFiles.push(fileName);
  };

  const ides = config?.ides || ['cursor', 'antigravity', 'claude', 'copilot'];

  // 1. Cursor Rules
  if (ides.includes('cursor')) {
    const cursorPath = join(dir, '.cursorrules');
    await ensureDir(cursorPath);
    await safeWrite(cursorPath, getCursorRules(stack, briefText), '.cursorrules');
  }

  // 2. Antigravity Global Rules & 3. Local Rules
  if (ides.includes('antigravity')) {
    const antigravityGlobalPath = join(homedir(), '.gemini', 'GEMINI.md');
    await ensureDir(antigravityGlobalPath);
    await generatedWrite(antigravityGlobalPath, getAntigravityRules(stack), 'Global Antigravity Rules (~/.gemini/GEMINI.md)');

    const antigravityLocalPath = join(dir, '.agent', 'rules', 'general.md');
    const localContent = getLocalAntigravityRules(stack, briefText);
    await generatedWrite(antigravityLocalPath, localContent, 'Local Antigravity Rules (.agent/rules/general.md)');
  }

  // 4. GitHub Copilot Instructions
  if (ides.includes('copilot')) {
    const copilotPath = join(dir, '.github', 'copilot-instructions.md');
    await ensureDir(copilotPath);
    await safeWrite(copilotPath, getCopilotInstructions(stack, briefText), '.github/copilot-instructions.md');
  }

  // 5. Claude Code / CLAUDE.md
  if (ides.includes('claude')) {
    const claudePath = join(dir, 'CLAUDE.md');
    await ensureDir(claudePath);
    await safeWrite(claudePath, getClaudeRules(stack, briefText), 'CLAUDE.md');
  }

  return createdFiles;
}
